[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dice"
version = "2025.6.30.2"
dependencies = []

[project.scripts]
dice = 'dice:main'

[tool.pytest.ini_options]
pythonpath = "src"
