[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "runmwe"
version = "2025.6.9.1"
dependencies = [
    "lsattr",
    "ooce",
]

[tool.pytest.ini_options]
pythonpath = "src"
