[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "requiresthat"
version = "2025.6.15.0"
dependencies = []

[tool.pytest.ini_options]
pythonpath = "src"
